const {
  withAppBuildGradle,
  withGradleProperties,
} = require("expo/config-plugins");

const START = "// @generated by Paprism withAbiSplits - do not edit";
const END = "// @end Paprism withAbiSplits";
const BLOCK = `${START}
    splits {
        abi {
            enable true
            reset()
            include "arm64-v8a", "armeabi-v7a", "x86_64"
            universalApk true
        }
    }
    ${END}`;

function addAbiSplits(contents) {
  if (contents.includes(START) && contents.includes(END)) return contents;
  if (contents.includes(START) || contents.includes(END)) {
    throw new Error("withAbiSplits found a partial generated block");
  }
  const matches = [...contents.matchAll(/^android\s*\{/gm)];
  if (matches.length !== 1) {
    throw new Error(
      `withAbiSplits expected one android block, found ${matches.length}`,
    );
  }
  return contents.replace(
    /^android\s*\{/m,
    (opening) => `${opening}\n    ${BLOCK}`,
  );
}

function setArchitectures(properties) {
  const key = "reactNativeArchitectures";
  const value = "armeabi-v7a,arm64-v8a,x86_64";
  const existing = properties.find(
    (item) => item.type === "property" && item.key === key,
  );
  if (existing) existing.value = value;
  else properties.push({ type: "property", key, value });
  return properties;
}

function withAbiSplits(config) {
  const withArchitectures = withGradleProperties(config, (result) => {
    result.modResults = setArchitectures(result.modResults);
    return result;
  });
  return withAppBuildGradle(withArchitectures, (result) => {
    if (result.modResults.language !== "groovy") {
      throw new Error("withAbiSplits only supports Groovy app/build.gradle");
    }
    result.modResults.contents = addAbiSplits(result.modResults.contents);
    return result;
  });
}

module.exports = withAbiSplits;
module.exports.addAbiSplits = addAbiSplits;
module.exports.setArchitectures = setArchitectures;
